### ISSUE TITLE
Implement a page layout

### ISSUE THREAD

**Issue by ecumene** [BTremb/Budget-calc-project#10]
- [ ] Remove all the occurrences of `width: ...` in your CSS
- [ ] Implement a full-page flex-box for your columns below:

HTML:
```html
      <div class="container">
        <div class="container-column-1">
          <div>Expenses:</div>
          <div>Payments:</div>
          <div>Total:</div>
        </div>
        <div class="container-column-2">
          <div class="row firstchild">
            Enter Monthly income:
            <input type="text" placeholder="Enter here" />
          </div>
        [ ... ] 
```

Container:
```css
.container {
    display: flex;
    flex-direction: row-reverse;
    gap: 2rem;
}
```

Column 2:
```css
.container-column-2 {
    display: flex;
    flex-direction: column;
    flex: 2;
}
```

Column 1:
```css
.container-column-1 {
    display: flex; 
    flex-direction: column;
    font-size: 175%;
    border-radius: 1rem;
    box-shadow: 0rem 0.2rem 0rem #131313;
    flex: 1;
}

.container-column-1 > * { 
    padding: 1.5rem;
    background-color: #f5ae5d;
    color: #030303;
}

.container-column-1 > *:first-child {
    border-top-right-radius: 1rem;
    border-top-left-radius: 1rem;
}

.container-column-1 > *:last-child {
    border-bottom-left-radius: 1rem;
    border-bottom-right-radius: 1rem;
}
```

![image](https://user-images.githubusercontent.com/6249465/215284339-da985009-d7c1-4163-b3ae-e5eaa970c6c2.png)
