### ISSUE TITLE
Remove all `id=` from your HTML: Replace them with classes

### ISSUE THREAD

**Issue by ecumene** [BTremb/Budget-calc-project#3]
https://github.com/BTremb/Budget-calc-project/blob/48592eb0a5df66b0669c606f33786d195055f4c9/Budget%20calc.html#L15

```html

<div class="column">
    <div class="row">row 1</div>
    <div class="row">row 2</div>
    <div class="row">row 3</div>
    <div class="row">row 4</div>
    <div class="row">row 5</div>
</div>

```
```css

.row {
    background-color: #f1f1f1;
    padding: 20px;
    margin: 20px 0;
}

.column:first-child {
    background-color: #aaa;
    padding: 20px;
    margin: 20px 0;
}

.column:last-child {
    background-color: #aaa;
    padding: 20px;
    margin: 20px 0;
}
```

- [ ] [Make a `.row` class](https://github.com/BTremb/Budget-calc-project/blob/48592eb0a5df66b0669c606f33786d195055f4c9/budget%20calculator%20stylesheet.css#L44)
