### ISSUE TITLE
Implement breakpoints

### ISSUE THREAD

**Issue by ecumene** [BTremb/Budget-calc-project#9]
- [ ] Read this: https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries

*In your HTML:*
```html
    <meta content="width=device-width, initial-scale=1" name="viewport" />
```

*In your stylesheet*
```css
@media screen and (max-width: 900px) {
    .container {
        flex-direction: column-reverse;
    }
}
```
